### get the token from making a POST in login.rest first
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{scniToken}}

{
  "title": "scni blog",
  "author": "scni",
  "url": "www.scni.com",
  "likes": 1
}

### get the token from making a POST in login.rest first
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{chefToken}}

{
  "title": "chef blog",
  "author": "chef",
  "url": "www.chef.com",
  "likes": 2
}